#Include *i %A_ScriptDir%\Script\Cando\Cando.ahk
#Include *i %A_ScriptDir%\Script\Cando\Cando_Hash.ahk
#Include *i %A_ScriptDir%\Script\Cando\Cando_提取图标.ahk
#Include *i %A_ScriptDir%\Script\Cando\Cando_Exif查看.ahk
#Include *i %A_ScriptDir%\Script\Cando\Cando_字符串处理.ahk
#Include *i %A_ScriptDir%\Script\Cando\Cando_脚本编译.ahk
#Include *i %A_ScriptDir%\Script\Cando\Cando_图像文件处理.ahk
#Include *i %A_ScriptDir%\Script\Cando\Cando_智能解压.ahk
#Include *i %A_ScriptDir%\Script\Cando\Cando_脚本查帮助.ahk
#Include *i %A_ScriptDir%\Script\Cando\Cando_有道网络翻译.ahk
#Include *i %A_ScriptDir%\Script\Cando\Cando_文件打开方式.ahk
#Include *i %A_ScriptDir%\Script\Cando\Cando_注册表跳转.ahk
#Include *i %A_ScriptDir%\Script\Cando\Cando_文件相关操作.ahk
#Include *i %A_ScriptDir%\Script\Cando\Cando_代码查看颜色.ahk
#Include *i %A_ScriptDir%\Script\Cando\Cando_文件创建软硬链接.ahk
#Include *i %A_ScriptDir%\Script\Cando\Cando_文件夹图标设置.ahk
#Include *i %A_ScriptDir%\Script\Cando\Cando_百度网络翻译.ahk
#Include *i %A_ScriptDir%\Script\Cando\Cando_Google网络翻译.ahk
#Include *i %A_ScriptDir%\Script\Cando\Cando_字符编码查看.ahk
#Include *i %A_ScriptDir%\Script\Cando\Cando_Msdn搜索.ahk
#Include *i %A_ScriptDir%\Script\Cando\Cando_十进制十六进制转换.ahk
#Include *i %A_ScriptDir%\Script\Cando\Cando_生成二维码.ahk
#Include *i %A_ScriptDir%\Script\Cando\Cando_添加单词到翻译文件.ahk
#Include *i %A_ScriptDir%\Script\Cando\Cando_文本比较.ahk
#Include *i %A_ScriptDir%\Script\Windo\Windo.ahk
#Include *i %A_ScriptDir%\Script\Windo\Windo_其他浏览器打开.ahk
#Include *i %A_ScriptDir%\Script\Windo\Windo_其他编辑器打开.ahk
#Include *i %A_ScriptDir%\Script\Hotkey\Explorer_文件属性.ahk
#Include *i %A_ScriptDir%\Script\Hotkey\Explorer_复制路径.ahk
#Include *i %A_ScriptDir%\Script\Hotkey\Explorer_定位文件.ahk
#Include *i %A_ScriptDir%\Script\Hotkey\Explorer_MD5.ahk
#Include *i %A_ScriptDir%\Script\Hotkey\Explorer_FastFolder.ahk
#Include *i %A_ScriptDir%\Script\Hotkey\Explorer_AppendFiles.ahk
#Include *i %A_ScriptDir%\Script\Hotkey\Explorer_智能重命名.ahk
#Include *i %A_ScriptDir%\Script\Hotkey\Explorer_用记事本打开.ahk
#Include *i %A_ScriptDir%\Script\Hotkey\Explorer_新建.ahk
#Include *i %A_ScriptDir%\Script\Hotkey\截取屏幕.ahk
#Include *i %A_ScriptDir%\Script\Hotkey\截取窗口.ahk
#Include *i %A_ScriptDir%\Script\Hotkey\快捷键_Plugins.ahk
#Include *i %A_ScriptDir%\Script\Hotkey\快捷键.ahk
#Include *i %A_ScriptDir%\Script\Hotkey\窗口水平垂直最大化.ahk
#Include *i %A_ScriptDir%\Script\Hotkey\窗口缩略图.ahk
#Include *i %A_ScriptDir%\Script\Hotkey\注册表.ahk
#Include *i %A_ScriptDir%\Script\Hotkey\Window Dragging KDE style.ahk
#Include *i %A_ScriptDir%\Script\Hotkey\Thumbnail.ahk
#Include *i %A_ScriptDir%\Script\Hotkey\Eval.ahk
#Include *i %A_ScriptDir%\Script\Hotkey\Explorer_剪贴板到文件.ahk
#Include *i %A_ScriptDir%\Script\Hotkey\git.ahk
#Include *i %A_ScriptDir%\Script\Hotkey\窗口程序和打开的文件.ahk
#Include *i %A_ScriptDir%\Script\Hotkey\Explorer_预览文件.ahk
#Include *i %A_ScriptDir%\Script\Hotkey\Explorer_显示隐藏文件.ahk
#Include *i %A_ScriptDir%\Script\7plus右键菜单\创建目录联接.ahk
#Include *i %A_ScriptDir%\Script\7plus右键菜单\百度搜索文件名.ahk
#Include *i %A_ScriptDir%\Script\7plus右键菜单\复制文件夹结构.ahk
#Include *i %A_ScriptDir%\Script\7plus右键菜单\智能解压.ahk
#Include *i %A_ScriptDir%\Script\7plus右键菜单\移动文件到同名文件夹.ahk
#Include *i %A_ScriptDir%\Script\7plus右键菜单\Open_Cmd_Here.ahk
#Include *i %A_ScriptDir%\Script\7plus右键菜单\记事本打开.ahk
